"use client";
import { useEffect, useState } from 'react';
import { AircraftLookup, type Lookup } from './AircraftLookup';

type Batch = {id:number;status:string;snapshot_date:string|null;imported_at:string|null;fetched_at:string|null;file_name:string;sha256:string;rows:number|null;error_message?:string;company_count?:number;site_count?:number;capability_count?:number};
export type Source = {code:string;name:string;group:string;method:string;regions:string[];countries:string[];fields:string[];match:string;readiness:string;url:string;cadence:string;refresh_days:number;scope:string;limitations:string;next_step:string;command:string;family:string;license?:string;attribution?:string;enabled?:boolean;schedule:string;has_import:boolean;latest_failed:boolean;freshness:{status:string;age_days:number|null};snapshot_date?:string;last_imported_at?:string;last_fetched_at?:string;record_count?:number;imported_countries?:string[];history:Batch[];lookups:Lookup[];settings?:{notes:string;updated_by:string;updated_at:string};field_coverage?:{rows:number;hex:number;tail:number;icao_type:number;category:number;rotorcraft:number};activity?:{processed_days:number;failed_days:number};latest_preview?:{query:string;fetched_at:string;truncated:string}};
type Inventory = {generated_at:string;sources:Source[];regions:Record<string,string>;history_note:string};
type GapRow = {region:string;aircraft:number;missing_tail:number;missing_type:number;missing_both:number;unclassified:number;rotorcraft:number;rotorcraft_missing_tail:number;recovered_tail:number};
type Gaps = {from:string;to:string;processed_days:number;expected_days:number;rows:GapRow[]};
export type GapReview = {region:string;from:string;to:string;gap:string};
const names:Record<string,string> = {GLOBAL:'Worldwide',EU:'Europe',NA:'North America',SA:'South America',AF:'Africa',AS:'Asia',OC:'Oceania',AN:'Antarctica',UNLOCATED:'No airport region'};
const groups:Record<string,string> = {IDENTITY:'Aircraft identity',COMPANY:'Companies & approvals',ACTIVITY:'Activity archives',REFERENCE:'Reference data'};
const states:Record<string,string> = {CURRENT:'Within review target',STALE:'Refresh due',UNKNOWN:'Source date unknown',NEVER:'No local snapshot',FUTURE:'Check future source date'};
const number = (n?:number|null) => n==null?'—':Number(n).toLocaleString();
const timestamp = (s?:string|null) => s?new Date(s).toLocaleString():'Not recorded';
function Status({s}:{s:Source}) {return <span className={`source-status status-${s.readiness==='PLANNED'?'planned':s.latest_failed?'stale':s.freshness.status.toLowerCase()}`}>{s.readiness==='PLANNED'?'Planned adapter':s.latest_failed?'Latest recorded attempt failed':states[s.freshness.status]}</span>;}
async function read<T>(url:string, signal?:AbortSignal):Promise<T> {const r=await fetch(url,{signal});const v=await r.json();if(!r.ok)throw new Error(v.error||'Could not load source evidence');return v;}

export function SourceHub({canEdit,onLba,onReview,initialSource='',onSourceChange}:{canEdit:boolean;onLba:()=>void;onReview:(request:GapReview)=>void;initialSource?:string;onSourceChange:(code:string)=>void}) {
  const [data,setData]=useState<Inventory|null>(null);
  const [error,setError]=useState('');
  const [revision,setRevision]=useState(0);
  const [query,setQuery]=useState('');
  const [group,setGroup]=useState('ALL');
  const [region,setRegion]=useState('ALL');
  const [attention,setAttention]=useState(false);
  const [selected,setSelected]=useState(initialSource);
  const [detail,setDetail]=useState<Source|null>(null);
  const [detailError,setDetailError]=useState('');
  const [gaps,setGaps]=useState<Gaps|null>(null);
  const [gapError,setGapError]=useState('');
  const [gapRequest,setGapRequest]=useState({from:'',to:'',revision:0});
  const [from,setFrom]=useState('');
  const [to,setTo]=useState('');
  const [gapBusy,setGapBusy]=useState(true);
  useEffect(()=>{const c=new AbortController();read<Inventory>('/api/tools/sources',c.signal).then(v=>{setData(v);setError('');}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[revision]);
  useEffect(()=>{
    if(!selected)return;
    const c=new AbortController();
    read<Source>(`/api/tools/sources/${encodeURIComponent(selected)}`,c.signal).then(setDetail).catch(e=>{if(!c.signal.aborted)setDetailError(e.message);});
    return()=>c.abort();
  },[selected,revision]);
  useEffect(()=>{
    const c=new AbortController();const params=new URLSearchParams();
    if(gapRequest.from)params.set('from',gapRequest.from);if(gapRequest.to)params.set('to',gapRequest.to);
    read<Gaps>(`/api/tools/identity-gaps?${params}`,c.signal).then(v=>{setGaps(v);setFrom(v.from);setTo(v.to);}).catch(e=>{if(!c.signal.aborted)setGapError(e.message);}).finally(()=>{if(!c.signal.aborted)setGapBusy(false);});
    return()=>c.abort();
  },[gapRequest]);
  function open(code:string){setSelected(code);setDetail(null);setDetailError('');onSourceChange(code);}
  function reload(){setError('');setRevision(n=>n+1);}
  if(selected)return <section className="source-workspace"><button onClick={()=>open('')}>← All sources</button>{detailError?<p role="alert">{detailError} <button onClick={()=>{setDetailError('');reload();}}>Retry source</button></p>:!detail?<p role="status">Loading source evidence…</p>:<SourceDetail key={`${detail.code}-${revision}`} source={detail} canEdit={canEdit} onLba={onLba} onSaved={()=>{setDetail(null);reload();}} />}</section>;
  const sources=data?.sources || [];
  const visible=sources.filter(s=>(group==='ALL'||s.group===group)&&(region==='ALL'||s.regions.includes(region)||s.regions.includes('GLOBAL'))&&(!attention||(s.readiness!=='PLANNED'&&(s.latest_failed||s.freshness.status!=='CURRENT')))&&`${s.name} ${s.code} ${s.scope} ${s.fields.join(' ')} ${s.countries.join(' ')} ${s.method} ${s.settings?.notes||''}`.toLowerCase().includes(query.toLowerCase()));
  const overall=gaps?.rows.find(r=>r.region==='GLOBAL');
  return <div className="source-hub">
    <section className="source-overview">
      <div><p className="eyebrow">Source coverage</p><h2>Know what is feeding Heligent.</h2><p>Inspect each source, see the age of its evidence, and choose the next gap to close.</p></div>
      <button onClick={reload}>Refresh source status</button>
    </section>
    {error && <p role="alert" className="map-warning">Source inventory unavailable: {error} <button onClick={reload}>Retry inventory</button></p>}
    {!data&&!error&&<p role="status">Loading imported sources…</p>}
    {data&&<>
      <div className="source-metrics"><article><strong>{sources.filter(s=>s.has_import).length}</strong><span>Sources with local imports</span></article><article><strong>{sources.filter(s=>s.freshness.status==='STALE'||s.latest_failed).length}</strong><span>Refresh due / failed attempt</span></article><article><strong>{sources.filter(s=>s.readiness!=='PLANNED'&&['NEVER','UNKNOWN','FUTURE'].includes(s.freshness.status)).length}</strong><span>Missing or uncertain source age</span></article><article><strong>{sources.filter(s=>s.readiness==='PLANNED').length}</strong><span>Adapters to build</span></article></div>
      <form className="source-filters" onSubmit={e=>e.preventDefault()}><label>Find a source<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, country code, field, notes…"/></label><label>Data purpose<select value={group} onChange={e=>setGroup(e.target.value)}><option value="ALL">All purposes</option>{Object.entries(groups).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Source region<select value={region} onChange={e=>setRegion(e.target.value)}><option value="ALL">All regions</option>{Object.entries(names).filter(([v])=>!['GLOBAL','UNLOCATED'].includes(v)).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="tools-check"><input type="checkbox" checked={attention} onChange={e=>setAttention(e.target.checked)}/> Needs attention</label></form>
      <p className="source-caption">{visible.length} of {sources.length} sources · Global sources are listed in every region; this does not mean complete country coverage. Review targets are local reminders, not schedules.</p>
      <div className="source-table-wrap"><table className="source-table"><thead><tr><th>Source / scope</th><th>Method / purpose</th><th>Identity fields</th><th>Source snapshot</th><th>Local evidence</th><th>Workspace</th></tr></thead><tbody>{visible.map(s=><tr key={s.code}><td><button className="source-name" onClick={()=>open(s.code)}>{s.name}</button><small>{s.countries.length?s.countries.join(', '):s.regions.map(r=>names[r]||r).join(', ')||'Scope not declared'}</small><Status s={s}/></td><td>{s.method}<small>{groups[s.group]}</small>{s.enabled===false&&<strong>Disabled source</strong>}</td><td>{s.fields.join(' · ')}<small>{s.match}</small></td><td>{s.snapshot_date||'Unknown'}<small>{s.freshness.age_days!=null?`${s.freshness.age_days} days old · ${s.refresh_days}-day target`:`${s.refresh_days}-day review target`}</small></td><td>{s.activity?`${number(s.activity.processed_days)} processed days`:s.readiness==='LOOKUP'?s.last_fetched_at?'Lookup evidence retained':'No lookups yet':s.has_import?`${number(s.record_count)} rows in latest import`:'No import recorded'}<small>{s.last_imported_at?`Imported ${timestamp(s.last_imported_at)}`:s.last_fetched_at?`Fetched ${timestamp(s.last_fetched_at)}`:s.readiness==='PLANNED'?'Adapter not built':'See workspace for next action'}</small></td><td><button onClick={()=>open(s.code)} aria-label={`Open ${s.name}`}>Open source →</button></td></tr>)}</tbody></table>{!visible.length&&<p className="source-empty">No sources match these filters.</p>}</div>
      <p className="source-caption">Status read {timestamp(data.generated_at)}. {data.history_note}</p>
    </>}
    <section className="tools-card source-gap-panel" aria-label="Identity coverage gaps"><p className="eyebrow">Observed aircraft · Resolved identity</p><h2>Where are tails and types still missing?</h2><p>Distinct hexes with at least one incomplete day in the selected period, after national register resolution. A missing ICAO type is separate from an unknown aircraft category.</p>
      <form onSubmit={e=>{e.preventDefault();setGapBusy(true);setGapError('');setGaps(null);setGapRequest({from,to,revision:gapRequest.revision+1});}}><label>Coverage from (UTC)<input type="date" required value={from} onChange={e=>setFrom(e.target.value)} disabled={gapBusy}/></label><label>Coverage to (UTC)<input type="date" required value={to} onChange={e=>setTo(e.target.value)} disabled={gapBusy}/></label><button disabled={gapBusy}>{gapBusy?'Checking coverage…':'Check gaps'}</button></form>
      {gapError&&<p role="alert" className="map-warning">Gap report unavailable: {gapError} <button onClick={()=>{setGapBusy(true);setGapError('');setGapRequest({...gapRequest,revision:gapRequest.revision+1});}}>Retry gap report</button></p>}
      {gaps&&overall&&<><p>{gaps.from} to {gaps.to} · {gaps.processed_days}/{gaps.expected_days} dates processed.{gaps.processed_days<gaps.expected_days?' Partial date coverage.':''}</p>
        <div className="source-metrics gap-metrics"><article><strong>{number(overall.missing_tail)}</strong><span>Hexes missing tails</span></article><article><strong>{number(overall.missing_type)}</strong><span>Hexes missing ICAO type</span></article><article><strong>{number(overall.unclassified)}</strong><span>Hexes with unknown category</span></article><article><strong>{number(overall.recovered_tail)}</strong><span>Tails supplied by registers</span></article></div>
        <div className="source-table-wrap"><table className="source-table gap-table"><thead><tr><th>Observed region</th><th>Hexes</th><th>No tail</th><th>No type</th><th>Neither</th><th>Unknown category</th><th>Helicopters without tails</th><th>National identity importers</th><th>Review</th></tr></thead><tbody>{['GLOBAL',...Object.keys(data?.regions||names).filter(r=>r!=='GLOBAL')].map(key=>{const r=gaps.rows.find(r=>r.region===key);const national=sources.filter(s=>s.group==='IDENTITY'&&s.readiness==='AVAILABLE'&&(key==='GLOBAL'||s.regions.includes(key)));return <tr key={key}><td><strong>{names[key]||key}</strong></td><td>{number(r?.aircraft||0)}</td><td>{number(r?.missing_tail||0)}</td><td>{number(r?.missing_type||0)}</td><td>{number(r?.missing_both||0)}</td><td>{number(r?.unclassified||0)}</td><td>{number(r?.rotorcraft_missing_tail||0)}</td><td>{key==='UNLOCATED'?'No location evidence':!data?'Source inventory unavailable':national.length?national.map(s=><small key={s.code}>{s.countries.join(', ')} · {s.has_import?'snapshot imported':'no snapshot'}{s.code==='CASA_AIRCRAFT_REGISTER'?' · tail match only':''}</small>):'No national adapter connected'}</td><td><button disabled={!r?.missing_tail} onClick={()=>onReview({region:key==='GLOBAL'?'ALL':key,from:gaps.from,to:gaps.to,gap:'TAIL'})}>Review tails</button><button disabled={!r?.missing_type} onClick={()=>onReview({region:key==='GLOBAL'?'ALL':key,from:gaps.from,to:gaps.to,gap:'TYPE'})}>Review types</button></td></tr>;})}</tbody></table></div>
        <p className="source-caption">Region comes from recorded airport visits, not registration country. A hex can appear in several regions; regional counts do not sum to worldwide totals. No airport region means no usable visit geography. Missing fields can occur on different days, so columns overlap. Registers cover their own countries, not whole continents.</p>
      </>}
    </section>
    <section className="tools-card source-next"><h3>The next useful sources</h3><p>Start with tar1090-db for bulk hex → tail/type candidates, then add national registers for dated confirmation. Mictronics and tar1090 share an upstream. ADSBdb and HexDB are available for individual checks; a second agreeing community lookup may still repeat the same original record.</p><div><button onClick={()=>open('TAR1090_DB')}>Inspect tar1090-db plan</button><button onClick={()=>open('UK_CAA_GINFO')}>Inspect UK register gap</button><button onClick={onLba}>Open LBA preview</button></div></section>
  </div>;
}

function SourceDetail({source:s,canEdit,onLba,onSaved}:{source:Source;canEdit:boolean;onLba:()=>void;onSaved:()=>void}) {
  const [days,setDays]=useState(s.refresh_days);
  const [notes,setNotes]=useState(s.settings?.notes||'');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  async function save(){setBusy(true);setError('');try{const r=await fetch(`/api/tools/sources/${encodeURIComponent(s.code)}/settings`,{method:'POST',headers:{'Content-Type':'application/json','X-Requested-With':'HeligentAdmin'},body:JSON.stringify({refresh_days:days,notes})});const v=await r.json();if(!r.ok)throw new Error(v.error||'Settings could not be saved');onSaved();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  return <>
    <header className="source-detail-header"><p className="eyebrow">{groups[s.group]} · {s.code}</p><h2>{s.name}</h2><Status s={s}/><p>{s.scope}</p><a href={s.url||undefined} target="_blank" rel="noreferrer">{s.url?'Open original source ↗':'Source link not recorded'}</a></header>
    <div className="source-detail-grid"><section className="tools-card"><h3>What this source supplies</h3><dl className="source-facts"><div><dt>Method</dt><dd>{s.method} · {s.readiness==='PLANNED'?'Adapter not built':s.readiness==='LOOKUP'?'Individual lookup available':'Importer available'}</dd></div><div><dt>Coverage</dt><dd>{s.countries.join(', ')||s.regions.map(r=>names[r]||r).join(', ')||'Not declared'}</dd></div><div><dt>Match key</dt><dd>{s.match}</dd></div><div><dt>Fields</dt><dd>{s.fields.join(' · ')}</dd></div><div><dt>Upstream family</dt><dd>{s.family}</dd></div><div><dt>Licence / attribution</dt><dd>{s.license||'See source terms; no licence recorded locally'}{s.attribution&&<small>{s.attribution}</small>}</dd></div></dl><p className="source-limitation">{s.limitations}</p>{s.imported_countries&&<p>Countries represented in imported sites: {s.imported_countries.join(', ')||'Not recorded'}. This is not a coverage guarantee.</p>}</section>
    <section className="tools-card"><h3>Freshness & collection</h3><dl className="source-facts"><div><dt>Latest successful source snapshot</dt><dd>{s.snapshot_date||'Unknown / no dated snapshot'}</dd></div><div><dt>Last imported</dt><dd>{timestamp(s.last_imported_at)}</dd></div><div><dt>Last fetched</dt><dd>{timestamp(s.last_fetched_at)}</dd></div><div><dt>Publisher cadence</dt><dd>{s.cadence}</dd></div><div><dt>Collection schedule</dt><dd>{s.schedule}</dd></div><div><dt>Review target</dt><dd>{s.refresh_days} days; applies to source snapshot age</dd></div></dl><p className="source-caption">Registry snapshot dates are recorded at import or supplied by the operator; publisher revision dates are not independently verified. Use the actual as-of date for retained files. Fetch time never fills an unknown source date. For API lookups, each record has its own fetch time; whole-database freshness is unknown.</p></section></div>
    {s.field_coverage&&<section className="tools-card"><h3>Fields in the latest imported snapshot</h3><p>{number(s.field_coverage.rows)} records. These are source records, not matches to observed aircraft.</p><div className="source-field-bars">{(['hex','tail','icao_type','category'] as const).map(key=><div key={key}><span>{{hex:'Hex address',tail:'Tail number',icao_type:'ICAO type',category:'Known category'}[key]}</span><meter min={0} max={s.field_coverage!.rows||1} value={s.field_coverage![key]} aria-label={key}/><strong>{number(s.field_coverage![key])} / {number(s.field_coverage!.rows)}</strong></div>)}</div><p>{number(s.field_coverage.rotorcraft)} rotorcraft records. Known category can identify helicopters even when an ICAO type is absent.</p></section>}
    <section className="tools-card"><h3>{s.readiness==='PLANNED'?'Next adapter to build':'Source tool'}</h3><p>{s.next_step}</p>{s.code==='LBA_DIRECTORY'&&<><button onClick={onLba}>Open LBA preview</button>{s.latest_preview&&<p>Last saved search: {s.latest_preview.query} at {timestamp(s.latest_preview.fetched_at)}. {s.latest_preview.truncated==='true'?'Search page was incomplete.':'Search page was complete; this is not the full directory.'}</p>}</>}{s.command&&<><p>Run on the Heligent server with its database configured:</p><pre className="source-command">{s.command}</pre><p className="source-caption">Commands are shown for the existing importer; opening this page does not run them. Registry importers also accept a retained ZIP with --file and --snapshot-date.</p></>}{s.code==='ADSB_LOL'&&<p>Open Data control in the top navigation to manage archive processing.</p>}</section>
    {s.readiness==='LOOKUP'&&<AircraftLookup provider={s.code} canEdit={canEdit}/>}
    <section className="tools-card"><h3>Local import history</h3>{!s.history.length?<p>No stored import batches. {s.readiness==='LOOKUP'?'Lookup results are separate review evidence, not imports.':s.readiness==='PLANNED'?'This adapter has not been built.':'An available importer is not evidence that it has been run.'}</p>:<div className="source-table-wrap"><table className="source-table"><thead><tr><th>Batch / status</th><th>Source as of</th><th>Imported</th><th>Rows</th><th>Evidence</th></tr></thead><tbody>{s.history.map(b=><tr key={b.id}><td>#{b.id}<small>{b.status}</small></td><td>{b.snapshot_date||'Not recorded'}</td><td>{timestamp(b.imported_at)}</td><td>{number(b.rows)}{b.site_count!=null&&<small>{b.company_count} companies · {b.site_count} sites · {b.capability_count} capabilities</small>}</td><td>{b.file_name}<details><summary>SHA-256</summary><code>{b.sha256}</code></details>{b.error_message&&<small>{b.error_message}</small>}</td></tr>)}</tbody></table></div>}<p className="source-caption">Latest 25 stored batches, ordered by source snapshot date for registers and batch order for company imports. Failed attempts that rolled back in older importers are not retained.</p></section>
    {!!s.lookups.length&&<section className="tools-card"><h3>Recent lookup evidence</h3><div className="source-table-wrap"><table className="source-table"><thead><tr><th>Hex</th><th>Outcome</th><th>Claimed tail / type</th><th>Fetched</th></tr></thead><tbody>{s.lookups.map(l=><tr key={l.id}><td><a href={l.source_url} target="_blank" rel="noreferrer">{l.address.toUpperCase()}</a></td><td>{l.status}<small>{l.result.error}</small></td><td>{l.result.registration||'—'} / {l.result.type_code||'—'}</td><td>{timestamp(l.fetched_at)}</td></tr>)}</tbody></table></div></section>}
    <section className="tools-card"><h3>Keep track of this source</h3><form onSubmit={e=>{e.preventDefault();void save();}}><label>Review interval (days)<input type="number" min={1} max={3650} required disabled={!canEdit||busy} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label className="source-notes">Coverage gaps / next steps<textarea maxLength={4000} disabled={!canEdit||busy} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Missing countries, mapping issues, next refresh, source contact…"/></label><button disabled={!canEdit||busy}>{busy?'Saving…':'Save source notes'}</button></form>{error&&<p role="alert">{error}</p>}{s.settings&&<p role="status">Saved by {s.settings.updated_by} · {timestamp(s.settings.updated_at)}</p>}<small>Notes and review interval are shared. This does not enable a schedule or change imported aircraft data.</small></section>
  </>;
}
