"""Source capabilities are explicit; operational status comes from stored evidence."""

REGIONS = {'EU': 'Europe', 'NA': 'North America', 'SA': 'South America',
           'AF': 'Africa', 'AS': 'Asia', 'OC': 'Oceania', 'AN': 'Antarctica',
           'UNLOCATED': 'No airport region'}


def source(code, name, *, group='IDENTITY', method='Bulk download', regions=('GLOBAL',),
           countries=(), fields=(), match='Hex address', readiness='AVAILABLE',
           url='', cadence='Not verified', refresh_days=30, scope='', limitations='',
           next_step='', command='', family=None):
    return dict(code=code, name=name, group=group, method=method, regions=list(regions),
                countries=list(countries), fields=list(fields), match=match,
                readiness=readiness, url=url, cadence=cadence, refresh_days=refresh_days,
                scope=scope, limitations=limitations, next_step=next_step,
                command=command, family=family or code)


CATALOG = [
    source('TC_CCAR', 'Transport Canada · CCAR', regions=('NA',), countries=('CA',),
           fields=('Tail', 'Hex', 'Model', 'Category'), match='Hex; dated registry evidence',
           url='https://wwwapps.tc.gc.ca/Saf-Sec-Sur/2/CCARCS-RIACC/DDZip.aspx?lang=eng',
           refresh_days=7, scope='Canadian civil aircraft. Official ZIP adapter and retained snapshots.',
           limitations='No ICAO designator imported. Registered owners are not treated as operators. Does not cover all North America.',
           next_step='Run a validated snapshot import on the Heligent server.',
           command='heligent-aircraft-registry sync-canada --dry-run\nheligent-aircraft-registry sync-canada'),
    source('FAA_AIRCRAFT_REGISTRY', 'United States · FAA', regions=('NA',), countries=('US',),
           fields=('Tail', 'Hex', 'Model', 'Category'), match='Hex; certificate/effective dates',
           url='https://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry/releasable_aircraft_download',
           cadence='Daily releasable database', refresh_days=7,
           scope='Eligible US civil master records joined to make/model reference.',
           limitations='Military, reserved and deregistered records are excluded. No ICAO designator imported. Owner is not operator.',
           next_step='Run a validated snapshot import on the Heligent server.',
           command='heligent-aircraft-registry sync-faa --dry-run\nheligent-aircraft-registry sync-faa'),
    source('CASA_AIRCRAFT_REGISTER', 'Australia · CASA', regions=('OC',), countries=('AU',),
           fields=('Tail', 'ICAO type', 'Model', 'Category', 'Registered operator'),
           match='Registration only — no hex in source',
           url='https://www.casa.gov.au/aircraft/aircraft-registration/data-files-registered-aircraft',
           refresh_days=7, scope='Australian civil aircraft; ZIP/CSV adapter and retained snapshots.',
           limitations='Cannot recover a missing tail directly from a hex. A tail from another source is needed first. Does not cover New Zealand or all Oceania.',
           next_step='Run a validated snapshot import on the Heligent server.',
           command='heligent-aircraft-registry sync-casa --dry-run\nheligent-aircraft-registry sync-casa'),
    source('TAR1090_DB', 'tar1090-db', fields=('Hex', 'Tail', 'ICAO type', 'Description', 'Flags'),
           readiness='BULK', family='MICTRONICS', refresh_days=14,
           url='https://github.com/wiedehopf/tar1090-db',
           cadence='On-demand download pinned to published GitHub revisions',
           scope='Global community cross-reference; retained aircraft.csv.gz and ICAO type reference. Helicopter-first comparison against observed gaps.',
           limitations='Shares the Mictronics upstream: agreement between these two is not independent confirmation. Current metadata does not establish historical assignments.',
           next_step='Download a reference snapshot, compare Europe gaps, then review individual candidates with verified effective dates.'),
    source('MICTRONICS', 'Mictronics aircraft database', fields=('Hex', 'Tail', 'ICAO type', 'Description'),
           readiness='PLANNED', family='MICTRONICS', refresh_days=14,
           url='https://github.com/Mictronics/aircraft-database', cadence='Weekly exports (publisher statement)',
           scope='Global downloadable JSON/ZIP exports, also used by tar1090-db.',
           limitations='Open Data Commons Attribution License. Use one bulk pipeline for this shared upstream; measure overlap, not source count.',
           next_step='Alternative input to the tar1090 bulk adapter. Preserve attribution and source snapshot.'),
    source('ADSBDB', 'ADSBdb', method='Individual API lookup', readiness='LOOKUP',
           fields=('Hex', 'Tail', 'ICAO type', 'Model', 'Manufacturer'),
           url='https://github.com/mrjackwills/adsbdb',
           scope='Global community aircraft lookup by hex, explicitly requested one aircraft at a time.',
           limitations='Coverage and per-record revision dates are unknown. A fetched response is a current claim, not historical proof. Owner fields are not imported.',
           next_step='Look up a hex below, compare the result, then use the dated identity review if appropriate.'),
    source('HEXDB', 'HexDB', method='Individual API lookup', readiness='LOOKUP',
           fields=('Hex', 'Tail', 'ICAO type', 'Model', 'Manufacturer'), url='https://hexdb.io/',
           cadence='Publisher: daily database refresh; upstream changes monthly',
           scope='Global community aircraft lookup, with cached responses.',
           limitations='Publisher explicitly prohibits database scraping. No bulk sweep or background enrichment. Coverage and per-aircraft revision dates are unknown.',
           next_step='Look up one hex below. Results and misses are cached for 30 days.'),
    source('UK_CAA_GINFO', 'United Kingdom · CAA G-INFO', method='Licensed file / mapping',
           regions=('EU',), countries=('GB',), readiness='PLANNED',
           fields=('Tail', 'Model', 'Category'), match='Confirm fields in licensed export',
           url='https://www.caa.co.uk/aircraft-register/g-info/g-info-download/',
           cadence='Monthly Excel product', refresh_days=35,
           scope='UK civil register. A priority national identity gap.',
           limitations='Bulk product is licensed, with restrictions on networking and redistribution. Confirm suitable rights and whether hex is included before an importer is built.',
           next_step='Obtain a suitable licensed sample; build a dedicated file preview and column mapping tool.'),
    source('OPENSKY_METADATA', 'OpenSky aircraft metadata', method='CSV / mapping', readiness='PLANNED',
           fields=('Hex', 'Tail', 'ICAO type', 'Model'), url='https://opensky-network.org/data/aircraft',
           scope='Global crowdsourced metadata with a downloadable CSV.',
           limitations='Uneven coverage and possible shared upstream records. Confirm applicable data terms and snapshot date; do not assume independent agreement.',
           next_step='Build a source-specific CSV preview with column validation, provenance and overlap reporting.'),
    source('LBA_DIRECTORY', 'Germany · LBA technical organisations', group='COMPANY',
           method='Selected organisation scrape', regions=('EU',), countries=('DE',),
           fields=('Approvals', 'Sites', 'Ratings', 'Model wording'), match='Approval number / exact company name',
           url='https://iauskunft.lba.de/tb/', scope='One complete search page; one selected DE.145 organisation per import.',
           limitations='Consent-based directory. Not a German aircraft register or full MRO census. Changed repeat imports require a merge workflow.',
           next_step='Fetch a named organisation, inspect every site, then import the selected organisation.'),
    source('ADSB_LOL', 'ADSB.lol historical traces', group='ACTIVITY', method='Archive ingestion',
           fields=('Activity', 'Reported tail', 'Reported type', 'Airport visits'), match='Hex + UTC day',
           url='https://github.com/adsblol/globe_history', cadence='Daily archives', refresh_days=2,
           scope='Processed historical days from direct downloads or the Raspberry Pi archive.',
           limitations='Receiver gaps and missing aircraft metadata remain possible. Processed days are not proof of complete surveillance.',
           next_step='Use Data control to queue missing days or inspect failed processing.'),
]
